#!/usr/bin/env python

# written by Soeren Gebbert
#
# COPYRIGHT:    (C) 1999,2007,2008 by the GRASS Development Team
#
#               This program is free software under the GNU General Public
#               License (>=v2). Read the file COPYING that comes with GRASS
#               for details.
#


#% Module
#%  description: Substracts a raster map with one or more raster maps
#%  keywords: raster
#%  keywords: math
#% End
#% option
#% key: inputs
#% type: string
#% gisprompt: old,cell,raster
#% description: Raster maps to substract. The first map will be substracted by the following maps.
#% required: yes
#% multiple: yes
#% end
#%option
#% key: output
#% type: string
#% gisprompt: new,cell,raster
#% description: The result of the mathematical operation
#% required : yes
#%END

import sys
import os
import grass.script as grass

def main():
    inputs = options['inputs']
    output = options['output']

    count = len(inputs.split(","))
 
    if count < 2:
        grass.fatal_error("At least two raster maps are needed")

    code = grass.run_command('r.mapcalc', expression=output + "=" + inputs.replace(",", "-"))

    if code != 0:
        raise IOError("Error while running r.mapcalc")

    # write cmd history:
    grass.raster_history(output)

if __name__ == "__main__":
    options, flags = grass.parser()
    main()
