python ../GrassAddons/r.add --wps-process-description > r.add.xml
python ../GrassAddons/r.sub --wps-process-description > r.sub.xml
python ../GrassAddons/r.div --wps-process-description > r.div.xml
python ../GrassAddons/r.mult --wps-process-description > r.mult.xml
python ../GrassAddons/r.math --wps-process-description > r.math.xml

#i.albedo --wps-process-description > i.albedo.xml
#i.atcorr --wps-process-description > i.atcorr.xml
#i.biomass --wps-process-description > i.biomass.xml
#i.cca --wps-process-description > i.cca.xml
#i.cluster --wps-process-description > i.cluster.xml
#i.eb.eta --wps-process-description > i.eb.eta.xml
#i.eb.evapfr --wps-process-description > i.eb.evapfr.xml
#i.eb.soilheatflux --wps-process-description > i.eb.soilheatflux.xml
#i.emissivity --wps-process-description > i.emissivity.xml
#i.evapo.time_integration --wps-process-description > i.evapo.time_integration.xml
#i.fft --wps-process-description > i.fft.xml
#i.fusion.brovey --wps-process-description > i.fusion.brovey.xml
#i.gensig --wps-process-description > i.gensig.xml
#i.gensigset --wps-process-description > i.gensigset.xml
#i.his.rgb --wps-process-description > i.his.rgb.xml
#i.ifft --wps-process-description > i.ifft.xml
#i.image.mosaic --wps-process-description > i.image.mosaic.xml
#i.landsat.acca --wps-process-description > i.landsat.acca.xml
#i.landsat.rgb --wps-process-description > i.landsat.rgb.xml
#i.landsat.toar --wps-process-description > i.landsat.toar.xml
#i.latlong --wps-process-description > i.latlong.xml
#i.maxlik --wps-process-description > i.maxlik.xml
#i.oif --wps-process-description > i.oif.xml
#i.pca --wps-process-description > i.pca.xml
#i.rgb.his --wps-process-description > i.rgb.his.xml
#i.smap --wps-process-description > i.smap.xml
#i.spectral --wps-process-description > i.spectral.xml
#i.sunhours --wps-process-description > i.sunhours.xml
#i.tasscap --wps-process-description > i.tasscap.xml
#i.vi --wps-process-description > i.vi.xml
#i.zc --wps-process-description > i.zc.xml

r.contour --wps-process-description > r.contour.xml
r.watershed --wps-process-description > r.watershed.xml
r.univar --wps-process-description > r.univar.xml
r.neighbors --wps-process-description > r.neighbors.xml
r.basins.fill --wps-process-description > r.basins.fill.xml
r.bitpattern --wps-process-description > r.bitpattern.xml
r.buffer --wps-process-description > r.buffer.xml
r.carve --wps-process-description > r.carve.xml
r.circle --wps-process-description > r.circle.xml
r.clump --wps-process-description > r.clump.xml
r.composite --wps-process-description > r.composite.xml
r.cost --wps-process-description > r.cost.xml
r.covar --wps-process-description > r.covar.xml
r.cross --wps-process-description > r.cross.xml
r.distance --wps-process-description > r.distance.xml
r.drain --wps-process-description > r.drain.xml
r.fill.dir --wps-process-description > r.fill.dir.xml
r.fillnulls --wps-process-description > r.fillnulls.xml
r.flow --wps-process-description > r.flow.xml
r.grow.distance --wps-process-description > r.grow.distance.xml
r.grow --wps-process-description > r.grow.xml
r.gwflow --wps-process-description > r.gwflow.xml
r.his --wps-process-description > r.his.xml
r.horizon --wps-process-description > r.horizon.xml
r.kappa --wps-process-description > r.kappa.xml
r.lake --wps-process-description > r.lake.xml
r.los --wps-process-description > r.los.xml
r.neighbors --wps-process-description > r.neighbors.xml
r.param.scale --wps-process-description > r.param.scale.xml
r.patch --wps-process-description > r.patch.xml
r.plane --wps-process-description > r.plane.xml
r.quant --wps-process-description > r.quant.xml
r.quantile --wps-process-description > r.quantile.xml
r.random.cells --wps-process-description > r.random.cells.xml
r.random --wps-process-description > r.random.xml
r.random.surface --wps-process-description > r.random.surface.xml
r.regression.line --wps-process-description > r.regression.line.xml
r.resamp.bspline --wps-process-description > r.resamp.bspline.xml
r.resamp.filter --wps-process-description > r.resamp.filter.xml
r.resamp.interp --wps-process-description > r.resamp.interp.xml
r.resamp.rst --wps-process-description > r.resamp.rst.xml
r.resamp.stats --wps-process-description > r.resamp.stats.xml
r.resample --wps-process-description > r.resample.xml
r.rescale --wps-process-description > r.rescale.xml
r.ros --wps-process-description > r.ros.xml
r.series --wps-process-description > r.series.xml
r.shaded.relief --wps-process-description > r.shaded.relief.xml
r.sim.sediment --wps-process-description > r.sim.sediment.xml
r.sim.water --wps-process-description > r.sim.water.xml
r.slope.aspect --wps-process-description > r.slope.aspect.xml
r.solute.transport --wps-process-description > r.solute.transport.xml
r.spread --wps-process-description > r.spread.xml
r.spreadpath --wps-process-description > r.spreadpath.xml
r.statistics --wps-process-description > r.statistics.xml
r.stats --wps-process-description > r.stats.xml
r.sun --wps-process-description > r.sun.xml
r.sunmask --wps-process-description > r.sunmask.xml
r.surf.area --wps-process-description > r.surf.area.xml
r.surf.contour --wps-process-description > r.surf.contour.xml
r.surf.gauss --wps-process-description > r.surf.gauss.xml
r.surf.idw --wps-process-description > r.surf.idw.xml
r.surf.idw2 --wps-process-description > r.surf.idw2.xml
r.surf.random --wps-process-description > r.surf.random.xml
r.terraflow --wps-process-description > r.terraflow.xml
r.texture --wps-process-description > r.texture.xml
r.thin --wps-process-description > r.thin.xml
r.to.vect --wps-process-description > r.to.vect.xml
r.topidx --wps-process-description > r.topidx.xml
r.topmodel --wps-process-description > r.topmodel.xml
r.transect --wps-process-description > r.transect.xml
r.univar --wps-process-description > r.univar.xml
r.uslek --wps-process-description > r.uslek.xml
r.usler --wps-process-description > r.usler.xml
r.volume --wps-process-description > r.volume.xml
r.walk --wps-process-description > r.walk.xml
r.water.outlet --wps-process-description > r.water.outlet.xml
v.buffer --wps-process-description > v.buffer.xml
v.class --wps-process-description > v.class.xml
v.delaunay --wps-process-description > v.delaunay.xml
v.distance --wps-process-description > v.distance.xml
v.drape --wps-process-description > v.drape.xml
v.extract --wps-process-description > v.extract.xml
v.extrude --wps-process-description > v.extrude.xml
v.generalize --wps-process-description > v.generalize.xml
v.hull --wps-process-description > v.hull.xml
v.kcv --wps-process-description > v.kcv.xml
v.kernel --wps-process-description > v.kernel.xml
v.krige --wps-process-description > v.krige.xml
v.lidar.correction --wps-process-description > v.lidar.correction.xml
v.lidar.edgedetection --wps-process-description > v.lidar.edgedetection.xml
v.lidar.growing --wps-process-description > v.lidar.growing.xml
v.mkgrid --wps-process-description > v.mkgrid.xml
v.neighbors --wps-process-description > v.neighbors.xml
v.net.alloc --wps-process-description > v.net.alloc.xml
v.net.allpairs --wps-process-description > v.net.allpairs.xml
v.net.bridge --wps-process-description > v.net.bridge.xml
v.net.centrality --wps-process-description > v.net.centrality.xml
v.net.components --wps-process-description > v.net.components.xml
v.net.connectivity --wps-process-description > v.net.connectivity.xml
v.net.distance --wps-process-description > v.net.distance.xml
v.net.flow --wps-process-description > v.net.flow.xml
v.net --wps-process-description > v.net.xml
v.net.iso --wps-process-description > v.net.iso.xml
v.net.path --wps-process-description > v.net.path.xml
v.net.salesman --wps-process-description > v.net.salesman.xml
v.net.spanningtree --wps-process-description > v.net.spanningtree.xml
v.net.steiner --wps-process-description > v.net.steiner.xml
v.net.timetable --wps-process-description > v.net.timetable.xml
v.net.visibility --wps-process-description > v.net.visibility.xml
v.normal --wps-process-description > v.normal.xml
v.outlier --wps-process-description > v.outlier.xml
v.out.vtk --wps-process-description > v.out.vtk.xml
v.overlay --wps-process-description > v.overlay.xml
v.parallel --wps-process-description > v.parallel.xml
v.patch --wps-process-description > v.patch.xml
v.perturb --wps-process-description > v.perturb.xml
v.random --wps-process-description > v.random.xml
v.rast.stats --wps-process-description > v.rast.stats.xml
v.reclass --wps-process-description > v.reclass.xml
v.report --wps-process-description > v.report.xml
v.sample --wps-process-description > v.sample.xml
v.segment --wps-process-description > v.segment.xml
v.select --wps-process-description > v.select.xml
v.split --wps-process-description > v.split.xml
v.surf.bspline --wps-process-description > v.surf.bspline.xml
v.surf.idw --wps-process-description > v.surf.idw.xml
v.surf.rst --wps-process-description > v.surf.rst.xml
v.to.points --wps-process-description > v.to.points.xml
v.to.rast --wps-process-description > v.to.rast.xml
v.transform --wps-process-description > v.transform.xml
v.univar --wps-process-description > v.univar.xml
v.voronoi --wps-process-description > v.voronoi.xml
t.rast.aggregate --wps-process-description > t.rast.aggregate.xml
t.rast.aggregate.ds --wps-process-description > t.rast.aggregate.ds.xml
t.rast.extract --wps-process-description > t.rast.extract.xml
t.rast.series --wps-process-description > t.rast.series.xml
t.rast.univar --wps-process-description > t.rast.univar.xml
t.sample --wps-process-description > t.sample.xml
t.info --wps-process-description > t.info.xml
t.topology --wps-process-description > t.topology.xml
t.rast.list --wps-process-description > t.rast.list.xml
#t.vect.extract --wps-process-description > t.vect.extract.xml
#t.vect.extract --wps-process-description > t.vect.extract.xml
#t.vect.observe.strds --wps-process-description > t.vect.observe.strds.xml
#t.vect.univar --wps-process-description > t.vect.univar.xml
#t.vect.what.strds --wps-process-description > t.vect.what.strds.xml
# --wps-process-description > .xml
